openapi: 3.0.0
info:
  title: Hello World API
  description: Hello World API
  version: 1.0.0
servers:
  - url: "/api"
paths:
  /notebook:
    get:
      operationId: api.notebook
      responses:
        "200":
          description: "Status of the notebook request checked successfully"
        "400":
          description: "Bad request, e.g. provided id of the Databricks job does not exist"
        "500":
          description: "Internal server error, the request failed"
  /validate:
    get:
      operationId: api.validate
      responses:
        "200":
          description: "Status of the validate request checked successfully"
        "400":
          description: "Bad request, e.g. provided id of the Databricks job does not exist"
        "500":
          description: "Internal server error, the request failed"
