@startuml
autonumber
actor       User       as end_user
participant "Orchestration Service" as orchestration_service
participant "Validation Service" as validation_service
database "Service A" as database_a
database "Service B" as database_b
Boundary "Databricks" as data_bricks
participant "Notebook" as notebook

end_user -> orchestration_service : ETL
orchestration_service -> validation_service : Validate
validation_service -> database_a : Validate Service A
validation_service -> database_b : Validate Service B
orchestration_service -> data_bricks : Invoke jobs
orchestration_service -> end_user : Job created
data_bricks -> notebook : Execute notebook

@enduml